"""Artifact packager node — assembles downloadable ZIP bundle."""

import io
import json
import zipfile
from datetime import datetime, timezone

import structlog

from agent.state import AgentState

logger = structlog.get_logger(__name__)


def _render_markdown_report(state: AgentState) -> str:
    """Render a human-readable Markdown compliance report."""
    report = state.get("compliance_report", {})
    pii = state.get("pii_report", {})
    vr = state.get("validation_result", {})
    warnings = state.get("warnings", [])

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    overall = report.get("overall_status", "unknown").upper()
    status_icon = {"PASS": "✅", "WARN": "⚠️", "FAIL": "❌"}.get(
        overall, "❓"
    )

    lines = [
        f"# ETL Optimization Report",
        f"",
        f"**Session:** `{state.get('session_id', 'n/a')}`  ",
        f"**Generated:** {ts}  ",
        f"**Target:** `{state.get('target', 'n/a')}`  ",
        f"**Input type:** `{state.get('input_type', 'n/a')}`  ",
        f"**Compliance:** `{state.get('compliance_profile', 'n/a')}`  ",
        f"",
        f"---",
        f"",
        f"## Overall Status: {status_icon} {overall}",
        f"",
    ]

    if warnings:
        lines += [f"## Warnings", ""]
        for w in warnings:
            lines.append(f"- ⚠️ {w}")
        lines.append("")

    lines += [
        f"## Compliance Checks",
        f"",
        f"| Rule ID | Name | Profile | Status | Detail |",
        f"|---------|------|---------|--------|--------|",
    ]
    for chk in report.get("checks", []):
        icon = {"pass": "✅", "warn": "⚠️", "fail": "❌"}.get(
            chk.get("status", ""), "❓"
        )
        lines.append(
            f"| {chk['id']} | {chk['name']} "
            f"| {chk['profile']} "
            f"| {icon} {chk['status'].upper()} "
            f"| {chk['detail']} |"
        )

    lines += [
        f"",
        f"## PII Summary",
        f"",
        f"- **Entities detected:** "
        + str(pii.get("entity_count", 0)),
        f"- **Risk level:** `{pii.get('risk_level', 'low')}`",
        f"- **Masked in output:** "
        + str(report.get("pii_summary", {}).get("masked_in_output")),
        f"",
        f"## Validation Result",
        f"",
        f"- **Passed:** {vr.get('passed', False)}",
        f"- **Syntax valid:** {vr.get('syntax_valid', False)}",
        f"- **Imports valid:** {vr.get('imports_valid', False)}",
        f"- **Execution time:** "
        + str(vr.get("execution_time_s", 0.0))
        + "s",
        f"- **Rows processed:** "
        + str(vr.get("synthetic_rows_processed", 0)),
    ]

    if vr.get("runtime_error"):
        lines += [
            f"",
            f"**Runtime error:** `{vr['runtime_error']}`",
        ]

    lines += [
        f"",
        f"## Audit Metadata",
        f"",
        f"- Audit columns added: "
        + ", ".join(
            f"`{c}`"
            for c in report.get("audit_columns_added", [])
        ),
        f"- Idempotency guard: "
        + str(report.get("idempotency_guard", False)),
        f"- Schema validation: "
        + str(report.get("schema_validation", False)),
        f"- Lineage metadata: "
        + str(report.get("lineage_metadata", False)),
        f"",
        f"---",
        f"*Generated by AI Agentic ETL Optimizer v1.0*",
    ]

    return "\n".join(lines)


def package_artifacts(state: AgentState) -> AgentState:
    """Package all output artifacts into an in-memory ZIP bundle."""
    session_id = state["session_id"]
    logger.info("packager_start", session_id=session_id)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        rewritten = state.get("rewritten_code", "")
        if rewritten:
            zf.writestr("rewritten.py", rewritten)

        diff = state.get("diff", "")
        if diff:
            zf.writestr("changes.diff", diff)

        compliance = state.get("compliance_report", {})
        if compliance:
            zf.writestr(
                "compliance_report.json",
                json.dumps(compliance, indent=2),
            )

        md_report = _render_markdown_report(state)
        zf.writestr("report.md", md_report)

        vr = state.get("validation_result", {})
        if vr:
            zf.writestr(
                "validation_result.json",
                json.dumps(vr, indent=2),
            )

        pii = state.get("pii_report", {})
        if pii:
            zf.writestr(
                "pii_report.json",
                json.dumps(pii, indent=2),
            )

    zip_bytes = buf.getvalue()
    logger.info(
        "packager_complete",
        session_id=session_id,
        zip_size_bytes=len(zip_bytes),
    )

    existing = dict(state)
    existing["_zip_bytes"] = zip_bytes
    existing["_markdown_report"] = md_report
    return existing
